# -*- coding: utf-8 -*-
"""1getExchangeRates_Frankfurter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-OloFH2bcxJPyPre1l4Ip1H6FoLEK0C

# Exchange Rate Sampling (Frankfurter)

This notebook:
1. Downloads historical FX rates from the Frankfurter API.
2. Fits a multivariate normal model in **log space** (⇒ lognormal in level space).
3. Draws **100 correlated FX scenarios**.
4. Saves the samples to `fx_draws_100.csv` (and optionally `fx_draws_100.pkl`).

**Rates convention:** Frankfurter returns rates as **currency units per 1 USD** when `base=USD`.  
Example: `EUR=0.92` means 1 USD = 0.92 EUR.
"""

# --- Imports ---
import numpy as np
import pandas as pd
import requests
from datetime import date

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)

"""## 1) Parameters"""

# --- Parameters you can edit ---
START_DATE = "2015-01-01"   # Historical start date (YYYY-MM-DD)
END_DATE   = None           # None => today
BASE       = "USD"          # Base currency
SYMBOLS    = ["BRL","EUR","INR","JPY","MXN"]  # Currencies to model
FREQ       = "M"            # Resample frequency: "D" daily, "W" weekly, "M" month-end
N_SAMPLES  = 100
SEED       = 123

# Sampling refinements
ANTITHETIC = True           # Variance reduction
WINSOR_Q   = (0.01, 0.99)   # Clip samples to historical quantiles to avoid extreme artifacts; set None to disable

"""## 2) Download historical rates from Frankfurter"""

def fetch_frankfurter_timeseries(start_date: str, end_date: str, base: str, symbols: list[str]) -> pd.DataFrame:
    """Fetch time series FX rates from Frankfurter API and return a DataFrame indexed by date.

    Frankfurter endpoint:
      https://api.frankfurter.app/<start>..<end>?from=<base>&to=<comma-separated symbols>

    Returns:
      DataFrame with columns = symbols, values = currency per 1 unit of base.
    """
    if end_date is None:
        end_date = date.today().isoformat()

    url = f"https://api.frankfurter.app/{start_date}..{end_date}"
    params = {"from": base, "to": ",".join(symbols)}
    r = requests.get(url, params=params, timeout=60)
    r.raise_for_status()
    data = r.json()

    # data["rates"] is a dict: { "YYYY-MM-DD": { "EUR": ..., "JPY": ... }, ... }
    rates_dict = data["rates"]
    df = pd.DataFrame.from_dict(rates_dict, orient="index").sort_index()
    df.index = pd.to_datetime(df.index)

    # Ensure all requested symbols are present (Frankfurter should return them, but keep defensive checks)
    df = df.reindex(columns=symbols)

    return df

hist = fetch_frankfurter_timeseries(START_DATE, END_DATE, BASE, SYMBOLS)
hist.head(), hist.tail()

"""## 3) Resample to a consistent frequency and clean"""

# Resample (month-end by default) and forward-fill to handle missing dates
if FREQ is not None:
    hist_rs = hist.resample(FREQ).last().ffill()
else:
    hist_rs = hist.copy()

# Drop any remaining missing values
hist_rs = hist_rs.dropna()

print("Shape (rows x cols):", hist_rs.shape)
hist_rs.describe()

"""## 4) Fit MVN in log space (lognormal in levels)"""

log_hist = np.log(hist_rs)

mu = log_hist.mean().values
Sigma = log_hist.cov().values

# Basic sanity checks
eigvals = np.linalg.eigvalsh(Sigma)
print("Min eigenvalue of covariance:", eigvals.min())
print("Currencies modeled:", list(hist_rs.columns))

"""## 5) Draw 100 correlated FX scenarios"""

def sample_fx_lognormal(
    n: int,
    mu: np.ndarray,
    Sigma: np.ndarray,
    columns: list[str],
    seed: int = 0,
    antithetic: bool = True,
    winsor_q: tuple[float, float] | None = (0.01, 0.99),
    hist_levels: pd.DataFrame | None = None
) -> pd.DataFrame:
    """Sample correlated FX levels using a lognormal model.

    Steps:
    1) Sample Z ~ MVN(mu, Sigma) in log space
    2) Return X = exp(Z) in level space

    Antithetic sampling:
      - Draw k = ceil(n/2), then mirror in log space around mu: Z' = 2*mu - Z
      - Improves Monte Carlo stability for estimated means/variances.

    Winsorization:
      - Optionally clips samples to historical quantiles to prevent extreme artifacts.
      - Requires hist_levels (level-space history) if enabled.
    """
    rng = np.random.default_rng(seed)
    k = (n + 1) // 2 if antithetic else n

    Z = rng.multivariate_normal(mean=mu, cov=Sigma, size=k)

    if antithetic:
        Z = np.vstack([Z, 2 * mu - Z])[:n]

    X = np.exp(Z)
    samples = pd.DataFrame(X, columns=columns)

    if winsor_q is not None:
        if hist_levels is None:
            raise ValueError("hist_levels must be provided when winsor_q is not None.")
        lo = hist_levels.quantile(winsor_q[0])
        hi = hist_levels.quantile(winsor_q[1])
        samples = samples.clip(lower=lo, upper=hi, axis=1)

    # Add USD = 1.0 to make downstream integration convenient
    samples["USD"] = 1.0
    return samples[[*columns, "USD"]]

fx_draws = sample_fx_lognormal(
    n=N_SAMPLES,
    mu=mu,
    Sigma=Sigma,
    columns=list(hist_rs.columns),
    seed=SEED,
    antithetic=ANTITHETIC,
    winsor_q=WINSOR_Q,
    hist_levels=hist_rs
)

fx_draws.head()

"""## 6) Save to disk for the Biopharma notebook"""

# CSV is the easiest format to share across notebooks
fx_draws.to_csv("fx_draws_100.csv", index=False)

# Optional: pickle preserves dtypes exactly
fx_draws.to_pickle("fx_draws_100.pkl")

print("Saved: fx_draws_100.csv and fx_draws_100.pkl")

"""## 7) Quick diagnostics (optional)"""

# Compare historical vs sampled summary stats (levels)
hist_summary = hist_rs.describe().T[["mean","std","min","max"]]
samp_summary = fx_draws[SYMBOLS].describe().T[["mean","std","min","max"]]

summary = hist_summary.join(samp_summary, lsuffix="_hist", rsuffix="_samp")
summary
