# -*- coding: utf-8 -*-
"""2Biopharma_solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103wJqqLTgbGt7c8uVqH6233BVYXjG7M0

<a href="https://colab.research.google.com/github/nosadchiy/public/blob/main/Biopharma_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biopharma

### Install and import packages
"""

# Packages
import pandas as pd
import numpy as np
from gurobipy import Model, GRB, quicksum
from tabulate import tabulate
import datetime as dt
import os

"""### Raw Data"""

selected_yr = 2023
base_yr = 2019

demand = pd.DataFrame({
    'from': ['LatinAmerica', 'Europe', 'AsiaWoJapan', 'Japan', 'Mexico', 'U.S.'],
    'd_h': [  7, 15,  5,  7,  3, 18],
    'd_r': [  7, 12,  3,  8,  3, 17],
})
demand.set_index('from', inplace=True)

caps = pd.DataFrame({
    'plant': ['Brazil', 'Germany', 'India', 'Japan', 'Mexico', 'U.S.'],
    'cap': [18, 45, 18, 10, 30, 22],
})
caps.set_index('plant', inplace=True)

pcosts = pd.DataFrame({
    'plant': ['Brazil', 'Germany', 'India', 'Japan', 'Mexico', 'U.S.'],
    'fc_p': [20, 45, 14, 13, 30, 23],
    'fc_h': [ 5, 13,  3,  4,  6,  5],
    'fc_r': [ 5, 13,  3,  4,  6,  5],
    'rm_h': [3.6, 3.9, 3.6, 3.9, 3.6, 3.6],
    'pc_h': [5.1, 6.0, 4.5, 6.0, 5.0, 5.0],
    'rm_r': [4.6, 5.0, 4.5, 5.1, 4.6, 4.5],
    'pc_r': [6.6, 7.0, 6.0, 7.0, 6.5, 6.5],
})
pcosts.set_index('plant', inplace=True)

tcosts = pd.DataFrame({
    'from': ['Brazil', 'Germany', 'India', 'Japan', 'Mexico', 'U.S.'],
    'LatinAmerica': [ 0.20, 0.45, 0.50, 0.50, 0.40, 0.45],
    'Europe':       [ 0.45, 0.20, 0.35, 0.40, 0.30, 0.30],
    'AsiaWoJapan':  [ 0.50, 0.35, 0.20, 0.30, 0.50, 0.45],
    'Japan':        [ 0.50, 0.40, 0.30, 0.10, 0.45, 0.45],
    'Mexico':       [ 0.40, 0.30, 0.50, 0.45, 0.20, 0.25],
    'U.S.':           [ 0.45, 0.30, 0.45, 0.45, 0.25, 0.20],
})
tcosts.set_index('from', inplace=True)

duties = pd.DataFrame({
    'from': ['LatinAmerica', 'Europe', 'AsiaWoJapan', 'Japan', 'Mexico', 'U.S.'],
    'duty': [ 0.30, 0.03, 0.27, 0.06, 0.35, 0.04],
})
duties.set_index('from', inplace=True)

# Your provided exchange_rate_data
exrate0 = {
    '2018': [3.88, 4.33, 69.63, 109.91, 19.64, 1],
    '2019': [4.33, 0.92, 71.48, 109.82, 18.65, 1],
    '2020': [5.19, 0.82, 73.66, 103.24, 19.90, 1],
    '2021': [5.26, 0.88, 74.28, 115.59, 20.62, 1],
    '2022': [5.29, 0.93, 82.75, 131.12, 19.48, 1],
    '2023': [4.85, 0.91, 83.04, 140.99, 16.96, 1],
}
exrate0 = pd.DataFrame(exrate0 , index=['BRL', 'EUR', 'INR', 'JPY', 'MXN', 'USD'])

"""# Minimize cost using Gurobi Binary and Integer optimizer

## Functions to calculate cost, unmet demand, and excess capacity
"""

# identify number of supply and demand location for iterations
n_ctry = range(demand.shape[0])
n_lines = range(demand.shape[1]+1)

# Objective function to calculate cost
def calc_total_cost(dec_plant, dec_h, dec_r, base_yr=2019, selected_yr=2023, tariff=0):
    x_plant = np.array(list(dec_plant.values())).reshape(len(n_ctry), len(n_lines))
    x_h = np.array(list(dec_h.values())).reshape(len(n_ctry), len(n_ctry))
    x_r = np.array(list(dec_r.values())).reshape(len(n_ctry), len(n_ctry))

    # Adjust the cost using exchange rate of give year
    reindx = exrate.loc[:, f'{base_yr}'] / exrate.loc[:, f'{selected_yr}']

    pcosts_rev = pcosts.values * reindx.values.reshape(-1,1)
    pcosts_rev = pd.DataFrame(pcosts_rev, columns=pcosts.columns[0:], index=pcosts.index)
    # return pcosts_rev
    # pcosts_rev = adj_pcosts_exrate(2019, 2023)

    duties_mat = np.zeros(len(duties)) + (1 + duties['duty'].values)[:, np.newaxis]
    np.fill_diagonal(duties_mat, 1)
    duties_mat = pd.DataFrame(duties_mat.T, index=pcosts_rev.index, columns=duties.index)
    duties_mat.loc['Germany', 'U.S.'] += tariff
    duties_mat.loc['U.S.', 'Europe']  += tariff

    vcosts_h = tcosts.add(pcosts_rev['rm_h'], axis=0).add(pcosts_rev['pc_h'], axis=0) * duties_mat
    vcosts_r = tcosts.add(pcosts_rev['rm_r'], axis=0).add(pcosts_rev['pc_r'], axis=0) * duties_mat

    fc = pcosts_rev[['fc_p','fc_h','fc_r']].values
    vh = (vcosts_h * x_h).values
    vr = (vcosts_r * x_r).values
    total_cost = sum(0.2 * fc[i,j] for i in n_ctry for j in n_lines) + sum(0.8 * fc[i,j] * x_plant[i,j] for i in n_ctry for j in n_lines) + sum(vh[i,j] for i in n_ctry for j in n_ctry) + sum(vr[i,j] for i in n_ctry for j in n_ctry)

    return total_cost


# Calculate excess capacity given decision variables
def calc_excess_cap(dec_plant, dec_h, dec_r):
    x_plant = np.array(list(dec_plant.values())).reshape(len(n_ctry), len(n_lines))
    x_h = np.array(list(dec_h.values())).reshape(len(n_ctry), len(n_ctry))
    x_r = np.array(list(dec_r.values())).reshape(len(n_ctry), len(n_ctry))

    excess_cap = (x_plant * caps.values).copy()
    excess_cap[:, 0] -= (np.sum(x_h, axis=1) + np.sum(x_r, axis=1))
    excess_cap[:, 1] -= np.sum(x_h, axis=1)
    excess_cap[:, 2] -= np.sum(x_r, axis=1)
    return excess_cap

# Calculate unmet demand given decision variables
def calc_unmet_demand(dec_h, dec_r):
    x_h = np.array(list(dec_h.values())).reshape(len(n_ctry), len(n_ctry))
    x_r = np.array(list(dec_r.values())).reshape(len(n_ctry), len(n_ctry))

    x_h_sum = np.sum(x_h, axis=0)
    x_r_sum = np.sum(x_r, axis=0)
    unmet_demand = (demand.values).copy()
    unmet_demand = np.column_stack((x_h_sum - unmet_demand[:, 0], x_r_sum - unmet_demand[:, 1]))

    return unmet_demand

"""## Gurobi optimizer

## Scenario-based network design (Part 1 & Part 2)

This completed notebook does **not** prompt for user input. It runs:

1. Loads 100 exchange-rate samples from `fx_draws_100.csv`
2. Solves the Biopharma network design problem for each scenario (plant/line decisions + flows)
3. Writes results and summary tables for strategy design:
   - Open frequencies for each plant/line
   - Most frequent configurations
   - Negative correlation pairs (potential hedging / substitution patterns)

**Next step (Part 3):** evaluate three fixed strategies in `Biopharma_FixedStrategyExample.ipynb`.
"""

# Part 1 & Part 2: Scenario-based optimization over sampled exchange rates
# ---------------------------------------------------------------------
# This notebook assumes you already generated `fx_draws_100.csv` from the
# completed getExchangeRates notebook and placed it in the same folder
# where you run this notebook.
#
# Output files (written to current working directory):
#   - biopharma_part1_results_res_df.csv
#   - biopharma_part2_open_rate.csv
#   - biopharma_part2_negative_pairs.csv
#   - biopharma_part2_top_configs.csv

# ----------------------------
# Configuration (no user input)
# ----------------------------
base_yr = 2019
selected_yr = 2023
tariff = 0.0          # set >0 if you want to evaluate a tariff scenario
n_scenarios = 100
seed = 123

# ----------------------------
# Load FX draws
# ----------------------------
fx_path = "fx_draws_100.csv"
if not os.path.exists(fx_path):
    raise FileNotFoundError(
        f"Missing {fx_path}. Run getExchangeRates_Frankfurter_COMPLETED.ipynb first "
        "to generate fx_draws_100.csv, then rerun this notebook."
    )

fx_draws = pd.read_csv(fx_path)
expected_cols = ["BRL","EUR","INR","JPY","MXN","USD"]
missing = [c for c in expected_cols if c not in fx_draws.columns]
if missing:
    raise ValueError(f"{fx_path} must contain columns {expected_cols}. Missing: {missing}")

# Keep exactly n_scenarios rows (in case file has more)
fx_draws = fx_draws.loc[:n_scenarios-1, expected_cols].copy()

# ----------------------------
# Build the optimization model ONCE
# ----------------------------
model = Model("Biopharma_ScenarioOptimization")
model.Params.OutputFlag = 0

# Decision variables
# Plant/line open decisions: (plant i) x (line j) where j = 0:Plant, 1:H, 2:R
dec_plant = {(i, j): model.addVar(vtype=GRB.BINARY, name=f"Dec_Plant_{i}_{j}")
             for i in n_ctry for j in n_lines}

# Flows for high and relaxed products: i -> j (plant i ships to market j)
dec_h = {(i, j): model.addVar(vtype=GRB.CONTINUOUS, lb=0, name=f"Dec_H_{i}_{j}")
         for i in n_ctry for j in n_ctry}
dec_r = {(i, j): model.addVar(vtype=GRB.CONTINUOUS, lb=0, name=f"Dec_R_{i}_{j}")
         for i in n_ctry for j in n_ctry}

# Constraints
# 1) Capacity (total, H line, R line) via excess capacity expression
excess_cap = calc_excess_cap(dec_plant, dec_h, dec_r)
for i in n_ctry:
    for j in n_lines:
        model.addConstr(excess_cap[i, j] >= 0, name=f"Cap_{i}_{j}")

# 2) Demand must be met exactly (unmet_demand == 0) for both H and R
unmet = calc_unmet_demand(dec_h, dec_r)
for i in n_ctry:
    for j in range(2):
        model.addConstr(unmet[i, j] == 0, name=f"Dem_{i}_{j}")

# 3) Logical linking: if line open then plant open (H->Plant, R->Plant)
#    dec_plant[i,0] is "Plant open", dec_plant[i,1] is "H line open", dec_plant[i,2] is "R line open"
for i in n_ctry:
    model.addConstr(dec_plant[i,1] <= dec_plant[i,0], name=f"Link_H_{i}")
    model.addConstr(dec_plant[i,2] <= dec_plant[i,0], name=f"Link_R_{i}")

model.update()

# ----------------------------
# Scenario loop: update exrate and objective, solve, and record open decisions
# ----------------------------
results = []
np.random.seed(seed)

for s in range(n_scenarios):
    # Update the exchange rates for the scenario by overwriting the 'selected_yr' column
    # exrate is a GLOBAL used by calc_total_cost()
    exrate = exrate0.copy()
    exrate.loc[:, f"{selected_yr}"] = fx_draws.loc[s, expected_cols].values

    # Update objective (scenario-specific)
    model.setObjective(calc_total_cost(dec_plant, dec_h, dec_r, base_yr, selected_yr, tariff), GRB.MINIMIZE)

    # Optimize
    model.optimize()

    # Record results
    row = {"scenario": s, "total_cost": float(model.objVal)}
    # Save plant/line decisions in a tidy way: PlantName_{Plant/H/R}
    plant_names = list(caps.index)  # ['Brazil','Germany','India','Japan','Mexico','U.S.']
    for idx, plant in enumerate(plant_names):
        row[f"{plant}_Plant"] = int(dec_plant[idx,0].X > 0.5)
        row[f"{plant}_H"]     = int(dec_plant[idx,1].X > 0.5)
        row[f"{plant}_R"]     = int(dec_plant[idx,2].X > 0.5)
    results.append(row)

res_df = pd.DataFrame(results)

# Save Part 1 results
res_df.to_csv("biopharma_part1_results_res_df.csv", index=False)

print("Part 1 complete: wrote biopharma_part1_results_res_df.csv")
print(res_df.head())

# ----------------------------
# Part 2: Summaries for proposing candidate strategies
# ----------------------------
decision_cols = [c for c in res_df.columns if c not in ["scenario","total_cost"]]

# Open frequency by plant/line (mean of 0/1)
open_rate = res_df[decision_cols].mean().sort_values(ascending=False)
open_rate.to_csv("biopharma_part2_open_rate.csv")

# Top configurations (most frequent combination of binaries)
# (Useful for reporting and sanity checks)
config_counts = (
    res_df[decision_cols]
    .astype(int)
    .value_counts()
    .reset_index()
    .rename(columns={0:"count"})
)
top_configs = config_counts.head(10)
top_configs.to_csv("biopharma_part2_top_configs.csv", index=False)

# Pairs that tend to open/close in opposition (negative correlation)
corr = res_df[decision_cols].corr()
pairs_neg = (
    corr.where(np.triu(np.ones(corr.shape), 1).astype(bool))
        .stack()
        .sort_values()
        .reset_index()
)
pairs_neg.columns = ["DecisionA","DecisionB","Correlation"]
pairs_neg.to_csv("biopharma_part2_negative_pairs.csv", index=False)

print("\nPart 2 summaries written:")
print(" - biopharma_part2_open_rate.csv")
print(" - biopharma_part2_top_configs.csv")
print(" - biopharma_part2_negative_pairs.csv")

print("\nTop 15 open rates:")
print(open_rate.head(15))

print("\nMost negative 15 pairs (potential 'either/or' relationships):")
print(pairs_neg.head(15))
