# -*- coding: utf-8 -*-
"""3Biopharma_FixedStrategyExample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3Pf4n3J8aEwIGzGj_wMOFfO3Pio4RPt

<a href="https://colab.research.google.com/github/nosadchiy/public/blob/main/Biopharma_FixedStrategyExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biopharma

### Install and import packages
"""

# Imports (assumes gurobipy is already installed and licensed)
import pandas as pd
import numpy as np
from gurobipy import Model, GRB
import os

"""### Raw Data"""

selected_yr = 2023
base_yr = 2019

demand = pd.DataFrame({
    'from': ['LatinAmerica', 'Europe', 'AsiaWoJapan', 'Japan', 'Mexico', 'U.S.'],
    'd_h': [  7, 15,  5,  7,  3, 18],
    'd_r': [  7, 12,  3,  8,  3, 17],
})
demand.set_index('from', inplace=True)

caps = pd.DataFrame({
    'plant': ['Brazil', 'Germany', 'India', 'Japan', 'Mexico', 'U.S.'],
    'cap': [18, 45, 18, 10, 30, 22],
})
caps.set_index('plant', inplace=True)

pcosts = pd.DataFrame({
    'plant': ['Brazil', 'Germany', 'India', 'Japan', 'Mexico', 'U.S.'],
    'fc_p': [20, 45, 14, 13, 30, 23],
    'fc_h': [ 5, 13,  3,  4,  6,  5],
    'fc_r': [ 5, 13,  3,  4,  6,  5],
    'rm_h': [3.6, 3.9, 3.6, 3.9, 3.6, 3.6],
    'pc_h': [5.1, 6.0, 4.5, 6.0, 5.0, 5.0],
    'rm_r': [4.6, 5.0, 4.5, 5.1, 4.6, 4.5],
    'pc_r': [6.6, 7.0, 6.0, 7.0, 6.5, 6.5],
})
pcosts.set_index('plant', inplace=True)

tcosts = pd.DataFrame({
    'from': ['Brazil', 'Germany', 'India', 'Japan', 'Mexico', 'U.S.'],
    'LatinAmerica': [ 0.20, 0.45, 0.50, 0.50, 0.40, 0.45],
    'Europe':       [ 0.45, 0.20, 0.35, 0.40, 0.30, 0.30],
    'AsiaWoJapan':  [ 0.50, 0.35, 0.20, 0.30, 0.50, 0.45],
    'Japan':        [ 0.50, 0.40, 0.30, 0.10, 0.45, 0.45],
    'Mexico':       [ 0.40, 0.30, 0.50, 0.45, 0.20, 0.25],
    'U.S.':           [ 0.45, 0.30, 0.45, 0.45, 0.25, 0.20],
})
tcosts.set_index('from', inplace=True)

duties = pd.DataFrame({
    'from': ['LatinAmerica', 'Europe', 'AsiaWoJapan', 'Japan', 'Mexico', 'U.S.'],
    'duty': [ 0.30, 0.03, 0.27, 0.06, 0.35, 0.04],
})
duties.set_index('from', inplace=True)

# Your provided exchange_rate_data
exrate0 = {
    '2018': [3.88, 4.33, 69.63, 109.91, 19.64, 1],
    '2019': [4.33, 0.92, 71.48, 109.82, 18.65, 1],
    '2020': [5.19, 0.82, 73.66, 103.24, 19.90, 1],
    '2021': [5.26, 0.88, 74.28, 115.59, 20.62, 1],
    '2022': [5.29, 0.93, 82.75, 131.12, 19.48, 1],
    '2023': [4.85, 0.91, 83.04, 140.99, 16.96, 1],
}
exrate0 = pd.DataFrame(exrate0 , index=['BRL', 'EUR', 'INR', 'JPY', 'MXN', 'USD'])

"""# Minimize cost using Gurobi Binary and Integer optimizer

## Functions to calculate cost, unmet demand, and excess capacity
"""

# identify number of supply and demand location for iterations
n_ctry = range(demand.shape[0])
n_lines = range(demand.shape[1]+1)

# Objective function to calculate cost
def calc_total_cost(dec_plant, dec_h, dec_r, base_yr=2019, selected_yr=2023, tariff=0):
    # reshape -> gives a new shape to an array without changing its data, changes shape of dictionary to a matrix
    # Plants Open / Shut, Lines On / Off (B54:D59)
    if isinstance(dec_plant, np.ndarray):
      x_plant = np.array(list(dec_plant.flatten())).reshape(len(n_ctry), len(n_lines))
    else:
      x_plant = np.array(list(dec_plant.values())).reshape(len(n_ctry), len(n_lines))
    # dec_h -> represents the quantities of highcal shipped from each supplier to each location (G54:L59)
    x_h = np.array(list(dec_h.values())).reshape(len(n_ctry), len(n_ctry))
    # dec_r -> represents the quantities of relax shipped from each supplier to each location (G63:L68)
    x_r = np.array(list(dec_r.values())).reshape(len(n_ctry), len(n_ctry))

    # Adjust the cost using exchange rate of give year
    # Base model -> reindx = exrate.loc[:, f'{base_yr}'] / exrate.loc[:, f'{selected_yr}']
    reindx = exrate.loc[:, f'{base_yr}'] / exrate.loc[:, f'{selected_yr}']

    pcosts_rev = pcosts.values * reindx.values.reshape(-1,1)
    pcosts_rev = pd.DataFrame(pcosts_rev, columns=pcosts.columns[0:], index=pcosts.index)

    # Matrix of the import duties, plus making the diagonals have no extra import duty hence equal to 1
    duties_mat = np.zeros(len(duties)) + (1 + duties['duty'].values)[:, np.newaxis]
    np.fill_diagonal(duties_mat, 1)

    # For the context of the problem there are only tariffs between north america and europe
    duties_mat = pd.DataFrame(duties_mat.T, index=pcosts_rev.index, columns=duties.index)
    duties_mat.loc['Germany', 'U.S.'] += tariff
    duties_mat.loc['U.S.', 'Europe']  += tariff

    # Variable costs Highcal
    vcosts_h = tcosts.add(pcosts_rev['rm_h'], axis=0).add(pcosts_rev['pc_h'], axis=0) * duties_mat
    # Variable costs Relax
    vcosts_r = tcosts.add(pcosts_rev['rm_r'], axis=0).add(pcosts_rev['pc_r'], axis=0) * duties_mat

    fc = pcosts_rev[['fc_p','fc_h','fc_r']].values
    vh = (vcosts_h * x_h).values
    vr = (vcosts_r * x_r).values
    total_cost = sum(0.2 * fc[i,j] for i in n_ctry for j in n_lines) + sum(0.8 * fc[i,j] * x_plant[i,j] for i in n_ctry for j in n_lines) + sum(vh[i,j] for i in n_ctry for j in n_ctry) + sum(vr[i,j] for i in n_ctry for j in n_ctry)

    return total_cost


# Calculate excess capacity given decision variables
def calc_excess_cap(dec_plant, dec_h, dec_r):
    condition = False
    if isinstance(dec_plant, np.ndarray):
      x_plant = np.array(list(dec_plant.flatten())).reshape(len(n_ctry), len(n_lines))
      condition = True
    else:
      x_plant = np.array(list(dec_plant.values())).reshape(len(n_ctry), len(n_lines))

    x_h = np.array(list(dec_h.values())).reshape(len(n_ctry), len(n_ctry))
    x_r = np.array(list(dec_r.values())).reshape(len(n_ctry), len(n_ctry))

    excess_cap = (x_plant * caps.values).copy()

    if condition:
      capacities = []
      for i in range(6):
        col = []
        col.append(excess_cap[i][0] - (np.sum(x_h, axis=1) + np.sum(x_r, axis=1))[i])
        col.append(excess_cap[i][1] - np.sum(x_h, axis=1)[i])
        col.append(excess_cap[i][2] - np.sum(x_r, axis=1)[i])
        capacities.append(col)
      return np.array(capacities)
    else:
      excess_cap[:, 0] -= (np.sum(x_h, axis=1) + np.sum(x_r, axis=1))
      excess_cap[:, 1] -= np.sum(x_h, axis=1)
      excess_cap[:, 2] -= np.sum(x_r, axis=1)
      return excess_cap

# Calculate unmet demand given decision variables
def calc_unmet_demand(dec_h, dec_r):
    x_h = np.array(list(dec_h.values())).reshape(len(n_ctry), len(n_ctry))
    x_r = np.array(list(dec_r.values())).reshape(len(n_ctry), len(n_ctry))

    x_h_sum = np.sum(x_h, axis=0)
    x_r_sum = np.sum(x_r, axis=0)
    unmet_demand = (demand.values).copy()
    unmet_demand = np.column_stack((x_h_sum - unmet_demand[:, 0], x_r_sum - unmet_demand[:, 1]))

    return unmet_demand

"""## Gurobi optimizer"""

# Configuration (defaults per assignment)
base_yr = 2019
selected_yr = 2023
tariff = 0.0

# Input files produced by Part 1/2 and FX sampling notebook
FX_SAMPLES_CSV = "fx_draws_100.csv"
OPEN_RATE_CSV  = "biopharma_part2_open_rate.csv"  # optional, used to auto-build strategies

# Load FX samples
if not os.path.exists(FX_SAMPLES_CSV):
    raise FileNotFoundError(f"Missing {FX_SAMPLES_CSV}. Place it in the same folder as this notebook.")

fx_draws = pd.read_csv(FX_SAMPLES_CSV)
required_cols = ["BRL","EUR","INR","JPY","MXN","USD"]
missing = [c for c in required_cols if c not in fx_draws.columns]
if missing:
    raise ValueError(f"{FX_SAMPLES_CSV} is missing columns: {missing}")

# Optionally load open rates (to build strategies programmatically)
open_rate = None
if os.path.exists(OPEN_RATE_CSV):
    tmp = pd.read_csv(OPEN_RATE_CSV)
    # expected format: columns ['Decision','OpenRate'] or two-column unnamed export; handle both
    if set(tmp.columns) >= {"Decision","OpenRate"}:
        open_rate = tmp.set_index("Decision")["OpenRate"]
    elif tmp.shape[1] >= 2:
        open_rate = pd.Series(tmp.iloc[:,1].values, index=tmp.iloc[:,0].astype(str).values)
    else:
        open_rate = None

print(f"Loaded FX samples: {fx_draws.shape[0]} scenarios")
print(f"Loaded open rates: {'yes' if open_rate is not None else 'no (will use built-in thresholds)'}")

"""Fixed Strategy Example (note that Total cost, Excess Capacity functions are modified to accommodate type change)"""

# Part 3 — Evaluate 3 fixed network strategies
#
# Each strategy fixes plant/line open decisions (Plant, H, R) and optimizes only shipment flows (Highcal, Relax)
# under 100 FX scenarios. We report expected cost and standard deviation.

plants = list(caps.index)  # ['Brazil','Germany','India','Japan','Mexico','U.S.']
lines  = ["Plant","H","R"]

def strategy_from_open_rates(open_rate_series, threshold_plant=0.5, threshold_line=0.5):
    """Build a 6x3 strategy matrix (order = plants, cols = Plant/H/R) from open-rate series."""
    mat = np.zeros((len(plants), 3), dtype=int)
    for i,p in enumerate(plants):
        for j,l in enumerate(lines):
            key = f"{p}_{l}" if l!="Plant" else f"{p}_Plant"
            rate = float(open_rate_series.get(key, 0.0))
            thr = threshold_plant if l=="Plant" else threshold_line
            mat[i,j] = int(rate >= thr)
    return mat

# ---- Define 3 candidate strategies ----
# Strategy A (Majority): open if open-rate >= 0.5
# Strategy B (Lean):     open if open-rate >= 0.8 (more selective, typically closes borderline sites/lines)
# Strategy C (Hedge):    start from Majority, then add a hedge line that tends to substitute (e.g., open U.S. Relax)

if open_rate is None:
    # Fallback if open rates file isn't present: use the rates reported in your console output.
    open_rate = pd.Series({
        "India_R":1.00,"Germany_Plant":1.00,"India_H":1.00,"India_Plant":1.00,
        "U.S._Plant":0.96,"Mexico_Plant":0.95,"Mexico_H":0.95,"Mexico_R":0.95,
        "Brazil_H":0.90,"Brazil_Plant":0.90,"Brazil_R":0.90,"Germany_R":0.83,
        "U.S._H":0.81,"Japan_Plant":0.75,"Japan_R":0.75,
        # others not listed assumed near 0
        "Germany_H":0.0,"Japan_H":0.0,"U.S._R":0.0
    })

strategy_A = strategy_from_open_rates(open_rate, threshold_plant=0.5, threshold_line=0.5)
strategy_B = strategy_from_open_rates(open_rate, threshold_plant=0.8, threshold_line=0.8)

strategy_C = strategy_A.copy()
# Hedge choice: open U.S. Relax line if it was mostly closed but can substitute for other lines under FX shifts
us_idx = plants.index("U.S.")
strategy_C[us_idx, 2] = 1  # U.S._R = 1

strategies = {
    "A_Majority": strategy_A,
    "B_Lean": strategy_B,
    "C_Hedge_USRelax": strategy_C
}

def pretty_strategy(mat):
    return pd.DataFrame(mat, index=plants, columns=lines)

for name,mat in strategies.items():
    print(f"\n{name} strategy (fixed open=1 / closed=0):")
    print(pretty_strategy(mat))

# ---- Evaluation function ----
def eval_fixed_strategy(dec_plant_fixed, fx_draws_eval):
    # Build LP once for this fixed network
    model = Model("FixedNetwork")
    model.Params.OutputFlag = 0

    # Decision variables: shipments from plant i to market j for Highcal and Relax
    dec_h = {(i, j): model.addVar(vtype=GRB.CONTINUOUS, lb=0, name=f"Dec_h_{i}_{j}") for i in n_ctry for j in n_ctry}
    dec_r = {(i, j): model.addVar(vtype=GRB.CONTINUOUS, lb=0, name=f"Dec_r_{i}_{j}") for i in n_ctry for j in n_ctry}

    # Constraints: capacity and demand satisfaction (reuse helper functions from earlier cells)
    excess_cap = calc_excess_cap(dec_plant_fixed, dec_h, dec_r)
    for i in n_ctry:
        for j in range(3):  # Plant, H, R
            model.addConstr(excess_cap[i, j] >= 0, name=f"Cap_{i}_{j}")

    unmet = calc_unmet_demand(dec_h, dec_r)
    for i in n_ctry:
        for j in range(2):  # Highcal, Relax
            model.addConstr(unmet[i, j] == 0, name=f"Demand_{i}_{j}")

    model.update()

    costs = []
    for s in range(len(fx_draws_eval)):
        # Update global exrate for this scenario (selected_yr column is overwritten)
        global exrate
        exrate = exrate0.copy()
        draw = fx_draws_eval.loc[s, ["BRL","EUR","INR","JPY","MXN","USD"]].values
        exrate.loc[:, f"{selected_yr}"] = draw

        model.setObjective(calc_total_cost(dec_plant_fixed, dec_h, dec_r, base_yr, selected_yr, tariff), GRB.MINIMIZE)
        model.optimize()
        costs.append(float(model.objVal))

    costs = np.array(costs, dtype=float)
    return costs.mean(), costs.std(ddof=1), costs

# ---- Run evaluation ----
summary_rows = []
all_costs = {}

for name, mat in strategies.items():
    mean_cost, sd_cost, costs = eval_fixed_strategy(mat, fx_draws)
    summary_rows.append({"Strategy": name, "ExpectedCost": mean_cost, "CostStdDev": sd_cost})
    all_costs[name] = costs
    print(f"\n{name}: mean={mean_cost:.4f}, sd={sd_cost:.4f}")

summary = pd.DataFrame(summary_rows).sort_values("ExpectedCost")
print("\nSummary (sorted by ExpectedCost):")
print(summary)

# Save outputs
summary.to_csv("biopharma_part3_strategy_summary.csv", index=False)
pd.DataFrame(all_costs).to_csv("biopharma_part3_strategy_costs_by_scenario.csv", index=False)

print("\nWrote:")
print(" - biopharma_part3_strategy_summary.csv")
print(" - biopharma_part3_strategy_costs_by_scenario.csv")

# Recommendation: lowest expected cost (tie-breaker: lower std dev)
best = summary.iloc[0]
print(f"\nRecommended strategy based on this Monte Carlo sample: {best['Strategy']}")

"""##### Conclusion: A_Majority and C_Hedge_USRelax have essentially identical expected cost on this 100-sample Monte Carlo run (difference ≈ 0.08). C shows slightly lower variability. Therefore, either A or C is reasonable; if risk aversion is considered, C is marginally preferable; otherwise A is acceptable."""
